name: cottage_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  provider: ^4.0.5
  shared_preferences: ^0.5.6+3
  fluttertoast: ^4.0.1
  uuid: ^2.0.4
  cloud_firestore: ^0.13.4+2
  geocoder: ^0.2.1
  location: ^3.0.2
  file_picker: ^1.9.0+1
  firebase_storage: ^3.1.6
  path_provider: ^1.6.10
  multi_media_picker: ^0.2.3
  trie: ^1.0.2
  fancy_bottom_navigation: ^0.3.2
  theme_provider: ^0.3.3
  curved_navigation_bar: ^0.3.2
  carousel_slider: ^2.1.0
  font_awesome_flutter: ^8.8.1
  multi_image_picker: ^4.6.7
  latlong: ^0.6.1
  geolocator: ^5.3.2+2
  url_launcher: ^5.4.10
  pretty_qr_code: ^1.0.1
  flutter_share: ^1.0.2+1
  flutter_full_pdf_viewer: ^1.0.6
  pdf: ^1.7.1
  qr_flutter: ^3.2.0
  barcode_scan: ^3.0.1
  flutter_screenutil: ^1.1.0
  neumorphic: ^0.3.0
  alan_voice: ^2.0.7
  bubble: ^1.1.9+1
  wiredash: ^0.2.0
  upi_india: ^2.1.2
  simple_animations: ^2.2.1
  webview_flutter: ^0.3.22+1
  google_sign_in: ^4.4.4
  image_picker: ^0.6.7+4
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/
          #   - images/a_dot_ham.jpeg
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Lobster
      fonts:
        - asset: fonts/Lobster-Regular.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
